name: Testing-workflow

on: push 

jobs:
  my-job:
    name: Testing-todo
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Deepak
        LAST_NAME: Bisht
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
